apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-simple
spec:
  consumerGroup: foooss
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: temperature-values-ce
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: source-display
