apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: groupOnie
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: sensor-data-test
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default
