apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source-enriched
spec:
  consumerGroup: yoyo
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: temperatures-enriched2
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default
